name: Mise a jour RPPS automatique

on:
  schedule:
    - cron: '0 8 * * 1' # Tous les lundis à 8h
  workflow_dispatch:      # Permet de le lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python recup_rpps.py

      - name: Commit and Push
        run: |
          git config --global user.name 'SDA-Bot'
          git config --global user.email 'bot@sda.fr'
          git add data_france.json
          git commit -m "Auto-update data_france.json" || exit 0
          git push
