name: Mise a jour RPPS automatique

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Version récente

      - name: Setup Python
        uses: actions/setup-python@v5 # Version récente
        with:
          python-version: '3.11' # Python plus rapide

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python recup_rpps.py

      - name: Commit and Push
        run: |
          git config --global user.name 'SDA-Bot'
          git config --global user.email 'bot@sda.fr'
          git add data_france.json
          git commit -m "Auto-update data_france.json" || exit 0
          git push
